name: Create a new release of the package

on:
  push:
    tags:
      - '*.*.*'

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.1.12
            - name: Build project for distribution
              working-directory: ./code
              run: poetry build
            - name: Extract module version from poetry
              shell: bash
              working-directory: ./code
              run: echo "##[set-output name=version;]$(poetry version --short)"
              id: module_poetry
            - name: Extract module version from tag
              shell: bash
              run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/})"
              id: module_tag
            - name: Check matchin names
              env:
                  POETRY_VERSION: ${{ steps.module_poetry.outputs.version }}
                  TAG_VERSION: ${{ steps.module_tag.outputs.version }}
              run: |
                [[ $POETRY_VERSION == $TAG_VERSION ]]
            - name: Check Version
              id: check-version
              working-directory: ./code
              run: |
                [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
                  || echo ::set-output name=prerelease::true
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "./code/dist/*"
                token: ${{ secrets.GITHUB_TOKEN }}
                draft: false
                prerelease: steps.check-version.outputs.prerelease == 'true'
            - name: Publish to PyPI
              working-directory: ./code
              env:
                POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI }}
              run: poetry publish
